# Site settings
name: Colorful的频道
email: wwd_study@163.com
author: Colorful_Wu
url: ''
resume_site: ''
github: https://github.com/Colorfu1/
baseurl: '/Colorful.io'
description: To be somebody!
meta_description: ''
motto: Brainy is the new sexy
banner: 时间已经让我们无法回头

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Colorfu1
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


theme: jekyll-theme-slate
